/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Shivam' at '8/4/21 4:48 PM' with Gradle 3.0
 *
 * @author Shivam, @date 8/4/21 4:48 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
