/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Shivam' at '7/31/21 3:25 PM' with Gradle 3.0
 *
 * @author Shivam, @date 7/31/21 3:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
